#!/usr/bin/env python3
"""
Ollama-based LLM-as-a-Judge for TCC/MTRAG generation outputs.

This judge is intended as a practical local alternative to the official RAGAS/HF
judge pipeline. It can use a model different from the generator, e.g.
qwen2.5:7b judging answers generated by llama3.1:8b, which reduces
self-evaluation bias.

Defaults:
  - Task C only, all domains and all TCC strategies.
  - Uses qwen2.5:7b via Ollama.
  - Resumable JSONL outputs: existing task_ids are skipped.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import random
import re
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


DOMAINS = ("fiqa", "clapnq", "cloud", "govt")
TASK_C_STRATEGIES = ("legacy", "small", "large", "multiscale", "noretrieval")
DEFAULT_BASE = Path("tcc_implementation/results/llama/llama3_1_8b_q4_ctx8192")
DEFAULT_MODEL = "qwen2.5:7b"
DEFAULT_OLLAMA_HOST = "http://127.0.0.1:11434"


def iter_jsonl(path: Path):
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                yield json.loads(line)


def append_jsonl(path: Path, row: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")
        f.flush()


def done_task_ids(path: Path) -> set[str]:
    if not path.is_file():
        return set()
    ids: set[str] = set()
    for row in iter_jsonl(path):
        task_id = row.get("task_id")
        if task_id:
            ids.add(str(task_id))
    return ids


def conversation_text(turns: Any, max_chars: int = 4000) -> str:
    if not isinstance(turns, list):
        return ""
    lines: list[str] = []
    for turn in turns:
        speaker = turn.get("speaker", "unknown") if isinstance(turn, dict) else "unknown"
        text = turn.get("text", "") if isinstance(turn, dict) else ""
        lines.append(f"{speaker}: {text}")
    text = "\n".join(lines)
    return text[-max_chars:]


def first_prediction(row: dict[str, Any]) -> str:
    preds = row.get("predictions") or []
    if isinstance(preds, list) and preds:
        first = preds[0]
        if isinstance(first, dict):
            return str(first.get("text", ""))
    return ""


def first_target(row: dict[str, Any]) -> str:
    targets = row.get("targets") or []
    if isinstance(targets, list) and targets:
        first = targets[0]
        if isinstance(first, dict):
            return str(first.get("text", ""))
    return ""


def contexts_text(row: dict[str, Any], max_contexts: int, max_context_chars: int) -> str:
    contexts = row.get("contexts") or []
    if not isinstance(contexts, list):
        return ""

    parts: list[str] = []
    for i, ctx in enumerate(contexts[:max_contexts], start=1):
        if not isinstance(ctx, dict):
            continue
        title = ctx.get("title") or ""
        doc_id = ctx.get("document_id") or ""
        text = str(ctx.get("text", ""))
        if len(text) > max_context_chars:
            text = text[:max_context_chars] + "..."
        header = f"[Context {i}]"
        if title or doc_id:
            header += f" title={title!r} document_id={doc_id!r}"
        parts.append(f"{header}\n{text}")
    return "\n\n".join(parts)


def build_prompt(
    row: dict[str, Any],
    *,
    domain: str,
    strategy: str,
    task: str,
    max_contexts: int,
    max_context_chars: int,
) -> str:
    return f"""You are an impartial evaluator for a Retrieval-Augmented Generation (RAG) benchmark.

Evaluate the assistant answer for the current multi-turn dialogue.
Use only the provided conversation, retrieved/reference contexts, and reference answer.

Return ONLY a valid JSON object with these exact keys:
{{
  "faithfulness": integer from 1 to 5,
  "answer_relevance": integer from 1 to 5,
  "context_usefulness": integer from 1 to 5,
  "completeness": integer from 1 to 5,
  "hallucination": "yes" | "no" | "partial",
  "justification": "one or two concise sentences"
}}

Scoring guidance:
- faithfulness: 5 means all factual claims are supported by the contexts/conversation; 1 means mostly unsupported.
- answer_relevance: 5 means the answer directly addresses the current user intent; 1 means irrelevant.
- context_usefulness: 5 means the contexts are sufficient/useful for the answer; 1 means not useful.
- completeness: 5 means the answer covers the important points in the reference answer; 1 means mostly incomplete.
- hallucination: "yes" if the answer invents unsupported facts, "partial" if some unsupported facts appear, otherwise "no".

Metadata:
task: {task}
domain: {domain}
strategy: {strategy}
task_id: {row.get("task_id", "")}

Conversation:
{conversation_text(row.get("input"))}

Reference answer:
{first_target(row)}

Assistant answer:
{first_prediction(row)}

Retrieved/reference contexts:
{contexts_text(row, max_contexts=max_contexts, max_context_chars=max_context_chars)}
"""


def extract_json_object(text: str) -> dict[str, Any]:
    cleaned = text.strip()
    cleaned = re.sub(r"^```(?:json)?", "", cleaned, flags=re.IGNORECASE).strip()
    cleaned = re.sub(r"```$", "", cleaned).strip()
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", cleaned, flags=re.DOTALL)
        if not match:
            raise
        candidate = match.group(0)
        try:
            return json.loads(candidate)
        except json.JSONDecodeError:
            repaired = re.sub(
                r"(?m)([\{,\s])"
                r"(faithfulness|answer_relevance|context_usefulness|completeness|hallucination|justification)\s*:",
                r'\1"\2":',
                candidate,
            )
            repaired = re.sub(r":\s*'(.*?)'", r': "\1"', repaired)
            repaired = re.sub(r":\s*(yes|no|partial)([\s,\}])", r': "\1"\2', repaired)
            return json.loads(repaired)


def normalize_score(value: Any) -> int | None:
    try:
        number = int(round(float(value)))
    except (TypeError, ValueError):
        return None
    return max(1, min(5, number))


def normalize_judgment(raw: dict[str, Any]) -> dict[str, Any]:
    hallucination = str(raw.get("hallucination", "")).strip().lower()
    if hallucination not in {"yes", "no", "partial"}:
        hallucination = "partial"
    return {
        "faithfulness": normalize_score(raw.get("faithfulness")),
        "answer_relevance": normalize_score(raw.get("answer_relevance")),
        "context_usefulness": normalize_score(raw.get("context_usefulness")),
        "completeness": normalize_score(raw.get("completeness")),
        "hallucination": hallucination,
        "justification": str(raw.get("justification", "")).strip(),
    }


def call_ollama(
    *,
    host: str,
    model: str,
    prompt: str,
    temperature: float,
    max_output_tokens: int,
    num_ctx: int,
    timeout: int,
    retries: int,
) -> tuple[dict[str, Any], str]:
    url = f"{host.rstrip('/')}/api/chat"
    payload = {
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "stream": False,
        "format": "json",
        "options": {
            "temperature": temperature,
            "num_predict": max_output_tokens,
            "num_ctx": num_ctx,
        },
    }

    last_error: Exception | None = None
    for attempt in range(retries + 1):
        req = urllib.request.Request(
            url,
            data=json.dumps(payload).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                data = json.loads(resp.read().decode("utf-8"))
            msg = data.get("message") or {}
            text = str(msg.get("content", ""))
            return normalize_judgment(extract_json_object(text)), text
        except urllib.error.HTTPError as exc:
            body = exc.read().decode("utf-8", errors="replace")
            last_error = RuntimeError(f"HTTP {exc.code}: {body[:500]}")
        except Exception as exc:
            last_error = exc

        sleep_s = min(60, (2**attempt) * 3) + random.random()
        print(f"Ollama judge call failed ({last_error}); retrying in {sleep_s:.1f}s", file=sys.stderr)
        time.sleep(sleep_s)

    assert last_error is not None
    raise last_error


def input_files_for_task(base: Path, task: str, domains: list[str], strategies: list[str]) -> list[tuple[str, str, Path]]:
    files: list[tuple[str, str, Path]] = []
    if task == "c":
        for domain in domains:
            for strategy in strategies:
                path = base / "evaluations" / "task_c" / domain / f"eval_c_{domain}_{strategy}.algonly.jsonl"
                files.append((domain, strategy, path))
    elif task == "b":
        for domain in domains:
            path = base / "evaluations" / "task_b" / f"eval_b_{domain}.algonly.jsonl"
            files.append((domain, "reference", path))
    else:
        raise ValueError(f"Unknown task: {task}")
    return files


def output_path_for(base: Path, task: str, domain: str, strategy: str, model: str) -> Path:
    model_slug = re.sub(r"[^A-Za-z0-9_.-]+", "_", model)
    if task == "c":
        return base / "evaluations" / "ollama_judge" / model_slug / "task_c" / domain / f"ollama_judge_c_{domain}_{strategy}.jsonl"
    return base / "evaluations" / "ollama_judge" / model_slug / "task_b" / f"ollama_judge_b_{domain}.jsonl"


def mean_score(rows: list[dict[str, Any]], key: str) -> float:
    values = [r.get(key) for r in rows if isinstance(r.get(key), int | float)]
    return round(sum(values) / len(values), 4) if values else 0.0


def rate_value(rows: list[dict[str, Any]], key: str, value: str) -> float:
    if not rows:
        return 0.0
    count = sum(1 for r in rows if r.get(key) == value)
    return round(count / len(rows), 4)


def summarize_outputs(base: Path, model: str) -> None:
    model_slug = re.sub(r"[^A-Za-z0-9_.-]+", "_", model)
    root = base / "evaluations" / "ollama_judge" / model_slug
    if not root.exists():
        return

    summary_rows: list[dict[str, Any]] = []
    for path in sorted(root.rglob("ollama_judge_*.jsonl")):
        rows = list(iter_jsonl(path))
        if not rows:
            continue
        task = str(rows[0].get("task", ""))
        domain = str(rows[0].get("domain", ""))
        strategy = str(rows[0].get("strategy", ""))
        judged = [r.get("ollama_judge", {}) for r in rows]
        summary_rows.append(
            {
                "task": task,
                "domain": domain,
                "strategy": strategy,
                "n": len(judged),
                "faithfulness_mean": mean_score(judged, "faithfulness"),
                "answer_relevance_mean": mean_score(judged, "answer_relevance"),
                "context_usefulness_mean": mean_score(judged, "context_usefulness"),
                "completeness_mean": mean_score(judged, "completeness"),
                "hallucination_yes_rate": rate_value(judged, "hallucination", "yes"),
                "hallucination_partial_rate": rate_value(judged, "hallucination", "partial"),
            }
        )

    if not summary_rows:
        return
    out = root / "summary.csv"
    with out.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(summary_rows[0].keys()))
        writer.writeheader()
        writer.writerows(summary_rows)
    print(f"Summary written to {out}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run Ollama LLM-as-a-Judge over MTRAG outputs.")
    parser.add_argument("--base", default=str(DEFAULT_BASE), help="Base result directory.")
    parser.add_argument("--model", default=DEFAULT_MODEL, help="Ollama judge model id.")
    parser.add_argument("--ollama-host", default=os.environ.get("OLLAMA_HOST", DEFAULT_OLLAMA_HOST))
    parser.add_argument("--tasks", nargs="+", default=["c"], choices=["b", "c"], help="Tasks to judge.")
    parser.add_argument("--domains", nargs="+", default=list(DOMAINS), choices=list(DOMAINS))
    parser.add_argument("--strategies", nargs="+", default=list(TASK_C_STRATEGIES), choices=list(TASK_C_STRATEGIES))
    parser.add_argument("--sleep-seconds", type=float, default=0.0, help="Delay between judge calls.")
    parser.add_argument("--max-contexts", type=int, default=5)
    parser.add_argument("--max-context-chars", type=int, default=1200)
    parser.add_argument("--max-output-tokens", type=int, default=512)
    parser.add_argument("--temperature", type=float, default=0.0)
    parser.add_argument("--num-ctx", type=int, default=8192)
    parser.add_argument("--timeout", type=int, default=600)
    parser.add_argument("--retries", type=int, default=3)
    parser.add_argument("--limit-per-file", type=int, default=None, help="Optional smoke-test limit per input file.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    base = Path(args.base)

    total_new = 0
    for task in args.tasks:
        for domain, strategy, input_path in input_files_for_task(base, task, args.domains, args.strategies):
            if not input_path.is_file():
                print(f"Skipping missing file: {input_path}", file=sys.stderr)
                continue

            output_path = output_path_for(base, task, domain, strategy, args.model)
            done_ids = done_task_ids(output_path)
            rows = list(iter_jsonl(input_path))
            if args.limit_per_file is not None:
                rows = rows[: args.limit_per_file]

            remaining = [row for row in rows if str(row.get("task_id")) not in done_ids]
            print(
                f"=== Ollama judge model={args.model} task={task} domain={domain} strategy={strategy} "
                f"({len(done_ids)} done, {len(remaining)} remaining, {len(rows)} total considered) ===",
                flush=True,
            )

            for idx, row in enumerate(remaining, start=1):
                prompt = build_prompt(
                    row,
                    domain=domain,
                    strategy=strategy,
                    task=task,
                    max_contexts=args.max_contexts,
                    max_context_chars=args.max_context_chars,
                )
                t0 = time.perf_counter()
                judgment, raw_response = call_ollama(
                    host=args.ollama_host,
                    model=args.model,
                    prompt=prompt,
                    temperature=args.temperature,
                    max_output_tokens=args.max_output_tokens,
                    num_ctx=args.num_ctx,
                    timeout=args.timeout,
                    retries=args.retries,
                )
                elapsed = time.perf_counter() - t0
                append_jsonl(
                    output_path,
                    {
                        "task_id": row.get("task_id"),
                        "conversation_id": row.get("conversation_id"),
                        "Collection": row.get("Collection"),
                        "task": task,
                        "domain": domain,
                        "strategy": strategy,
                        "judge_model": args.model,
                        "ollama_judge": judgment,
                        "raw_response": raw_response,
                        "elapsed_sec": round(elapsed, 3),
                    },
                )
                total_new += 1
                print(
                    f"  {idx}/{len(remaining)} {row.get('task_id')} "
                    f"faithfulness={judgment.get('faithfulness')} "
                    f"relevance={judgment.get('answer_relevance')} "
                    f"({elapsed:.1f}s)",
                    flush=True,
                )
                if args.sleep_seconds > 0:
                    time.sleep(args.sleep_seconds)

    summarize_outputs(base, args.model)
    print(f"Done. New judgments written: {total_new}")


if __name__ == "__main__":
    main()
